    optimus-config:
      enabled: true
      loyaltyRewardId: 123456
      filterLoyaltyReward: true
      promotionName: Vital Care Rewards
      promotionType: LOYALTY REWARD
      promotionIdStartWith: Pals_Reward
      promotionIdEndWith: PRM
      promoCodeIdStartWith: PalsReward_
      loyaltyPromotionFlag: true
      promptUserFlag: true
